### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#15]
## Plugin Request

**Name**: PDF Viewer
**Package**: `@capacitor-community/pdf-viewer`

### Platform(s)

Android, iOS

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/374

**Comment by johnbraum** [comment]
Do we really need a plugin for that? I did this one for a PWA and just used the pdf.js framework for that. Inclusive search, pages overview, etc.

**Comment by dwieeb** [comment]
I was also wondering that. @TrayserCassa any advantages of a native solution that we're not seeing?

**Comment by johnbraum** [comment]
One point could be the size of the application.

**Comment by TrayserCassa** [comment]
@johnbraum 
It is mostly because I didn't know much about web programming. So a small guide would be nice.
But I didn't care anymore, because our Company cancelled the new App and now I am working where I want to be. I Like the Project and some private Projects are written in Ionic, so it is not the fault of the Framework and your work.

**Comment by khaledosman** [comment]
pdfjs is huge in size and is an overkill, the original goal is to be able to view pdf files inside the inapp browser similar to how the web browser handles it, this already works well using `Browser.open` for iOS, but not for android, so my current workaround for android is to download the file then view it using a combination of Capacitor's `FileSystem` and `@ionic-native/file-opener` which is also not optimal due to download time and taking disk space on the user's phone

**Comment by imhoffd** [comment]
I created https://github.com/ionic-team/capacitor-docs/issues/58 to track the development of a tutorial for viewing PDFs in Capacitor.

Thanks for responding @TrayserCassa! I'll close this until someone can respond with advantages of a native solution.
