### ISSUE TITLE
Adyen Payment SDK

### ISSUE THREAD

**Issue by Geschan** [capacitor-community/proposals#185]
## Plugin Request

**Name**: Adyen
**Package**: `@capacitor-community/adyen`

### Platform(s)

- iOS
- Android

### Existing Solutions

https://github.com/foodji/capacitor-adyen

Currently maintained by me

### Description

Plugin for the mobile SDKs of the payment provider [Adyen](https://en.wikipedia.org/wiki/Adyen) (used by Spotify, Netflix, Uber and others).

**Comment by kristofferdamborg** [comment]
@Geschan

The existing solution ([https://github.com/foodji/capacitor-adyen](https://github.com/foodji/capacitor-adyen)) you mentioned no longer seems to be active.
Would you happen to have a copy of the code so I can take a look at how you built the solution? Would really appreciate the help! 😄

**Comment by eljass** [comment]
@kristofferdamborg we just released few minutes ago solution to use Adyen Card component. We only needed card component as Adyen web component does not work on custom scheme. 

Would that work for your needs as well? If so, we are happy to hear any feedback!

https://www.npmjs.com/package/@foodello/capacitor-adyen

**Comment by kristofferdamborg** [comment]
@eljass Thanks! That’s really helpful — I can definitely take some inspiration from that. I was considering using the drop-in integration instead of individual components. Do you know if that causes any issues in a Capacitor app? :)

**Comment by eljass** [comment]
@kristofferdamborg I think it should be doable pretty much similar way than card component. I would maybe suggest looking into Android code of that plugin, as I feel iOS a bit more messy at this moment.

The main idea for structure was:
- Plugin methods -file
  - Contains first touch point when calling plugin methods from web (for example `presentCardComponent`)
- Implementation -file
  - Includes wrapper for all the possible components, shares methods that are present on multiple Adyen component (for example `hideComponent`)
  - We can store currently active component here to be reused elsewhere
- Specific Adyen components' code:
  - Each component requires a bit different logic and handling, so it would be smart to keep them seperate to improve readability/maintainability.
- Then we have different files for utils and helpers

So flow is like (for example `Adyen.presentCardComponent()`):
Web -> Plugin methods -file -> Implementation -file -> Specific Adyen Component code

---

In this example, then integrating DropIn component would in theory be:

1. Add implementation for gradle file (and required dependencies for Pod file and SiftPackages (for iOS))
2. Implement `presentDropInComponent` method in "Plugin methods" -file and typescript type definitions
3. Add required changes to "Implementation" -file
4. Build logic for DropIn component into "components" folder

Very brief consept on Android for example:

build.gradle:
``` diff
implementation "com.adyen.checkout:card:$adyenVersion"
+ implementation "com.adyen.checkout:drop-in:$adyenVersion"
```

./android/src/main/java/com/foodello/adyen/AdyenPlugin.kt:
```diff
+ @PluginMethod
+ fun presentDropInComponent(call: PluginCall) {
+     val amount = call.getInt("amount")
+     val countryCode = call.getString("countryCode")
+     val currencyCode = call.getString("currencyCode")
+     val configuration = call.getObject("configuration")
+     val style = call.getObject("style")
+     val viewOptions = call.getObject("viewOptions")
+ 
+     try {
+         implementation.presentDropInComponent(
+                 amount = amount,
+                 countryCode = countryCode,
+                 currencyCode = currencyCode,
+                 configuration = configuration,
+                 style = style,
+                 viewOptions = viewOptions
+         )
+         call.resolve()
+     } catch (e: Exception) {
+         call.reject("Failed to present drop-in component: ${e.message}")
+     }
+ }
```

./android/src/main/java/com/foodello/adyen/AdyenImplementation.kt
```diff
+ // Have to do something for types here
private var activeComponent: AdyenCardComponent? = null

+ fun presentDropInComponent(
+         amount: Int?,
+         countryCode: String?,
+         currencyCode: String?,
+         configuration: JSObject?,
+         style: JSObject?,
+         viewOptions: JSObject?
+ ) {
+   // Add logic here (take inspiration of presentCardComponent function)
+ }
```

./android/src/main/java/com/foodello/adyen/components/AdyenDropinComponent.kt
```kotlin
// Get inspiration of AdyenCardComponent.kt
// the logic difference does not seem too different between these two

// 1. create -function to prepare configs: https://docs.adyen.com/online-payments/build-your-integration/advanced-flow?platform=Android&integration=Drop-in&version=5.14.0&tab=nodejs_3_4#configure

// 2. Create callback handlers to pass events to Capacitor.js app (can use adyenPlugin.onEvent)

// 3. present function (can take inspiration from card component how it is shown inside custom bottom sheet)
```

On events we get from DropIn component to the web app, we can then handle those with adyen-web sdk, or otherwise we would need to implement other native components for:

- Redirect (fairly simple to handle, but can also be handled with WebViews, Android Custom Tabs etc)
- 3DS2 authentication (could also be handled with redirect in most cases)
- QR code action
- SDK action
- Voucher action
- Await action

---

That being said, if you feel like forking our plugin, feel free to open PR if you get it working. It might take some time from us to extend current solutions as we mainly needed Card component only and are going live with it soon. :)

**Comment by kristofferdamborg** [comment]
@eljass You mentioned that the Adyen Web Component doesn’t work with a custom scheme — could you clarify what you mean by that?
I’m wondering whether it’s possible to use the web version of the Drop-in natively on iOS and Android, with advanced flow, without any restrictions, or if you’re aware of any issues with that setup?

**Comment by eljass** [comment]
@kristofferdamborg We use advanced flow with custom components. The issue was that web compinent's secured fields for card inputs fails as capacitor scheme (protocol) is not `https://` but `capacitor://`. It is not marked as "secure" by Adyen.

That was the reason we built the plugin for Card component only at first. Other payment components worked correctly with web solution as they mainly redirect to external browser.

Our workflow is to modify default component to show loader on native apps and open card inputs with Adyen native components (it opens native bottom sheet styled window on top of the app). And then listen card submission to be passed to Web advanced flow's `onSubmit`. To be noted that we use seperate "Pay" button in our UX. 

We also open redirect in capgo/inappbrowser's WebView as it is customizable.

I could not take screenshot of card component itself as there is privacy shield on it by Adyen.

<img src="https://github.com/user-attachments/assets/e2976cd8-34ea-44fd-a5dc-78210bea343d" width="20%">

<img src="https://github.com/user-attachments/assets/0df3aee5-8aa7-49c8-a8a2-4cc1e3d6be5d" width="20%">

<img src="https://github.com/user-attachments/assets/95e32bb7-1e86-4200-b9b2-d05c803c8cd6" width="20%">

<img src="https://github.com/user-attachments/assets/03faf312-51ab-4d81-8fa7-b42ce0b9be2b" width="20%">

**Comment by eljass** [comment]
To be added, this issue was only with production environment. Adyen test environment worked also with Web components in iOS.

**Comment by kristofferdamborg** [comment]
@eljass Thank you again for the answers! Maybe using your plugin is actually the solution to my problems then 🙌 

> To be added, this issue was only with production environment. Adyen test environment worked also with Web components in iOS.'

Oh, I see. So the issue only occurs on iOS? All web components work fine on Android since it runs on the `https` scheme?

> Our workflow is to modify default component to show loader on native apps and open card inputs with Adyen native components (it opens native bottom sheet styled window on top of the app). And then listen card submission to be passed to Web advanced flow's onSubmit. To be noted that we use seperate "Pay" button in our UX.

Don't you also need to handle the `onAdditionalDetails` event when using the advanced flow? And how do you handle the result of these events (when `actions.resolve()` and `actions.reject()` in not available)?

> We also open redirect in capgo/inappbrowser's WebView as it is customizable.

How do you handle that?

**Comment by eljass** [comment]
> Oh, I see. So the issue only occurs on iOS? All web components work fine on Android since it runs on the https scheme?

@kristofferdamborg for us it was only for iOS as we actually define Android's scheme to be `https://` with these capacitor configs:

```typescript
const config: CapacitorConfig = {
    // ... other capacitor configs
    server: {
        iosScheme: 'myapp', // used some placeholder here for this example
        androidScheme: 'https',
        // ..other server configs
    }
}
```

If you use default configurations for Capacitor the schemes are as:
- Android: `https://`
- iOS: `capacitor://`

[source](https://capacitorjs.com/docs/config#:~:text=/**%0A%20%20%20%20%20*%20Configure%20the%20local%20scheme,androidScheme%3F%3A%20string%3B)

> Don't you also need to handle the onAdditionalDetails event when using the advanced flow? And how do you handle the result of these events (when actions.resolve() and actions.reject() in not available)?

We use only `redirect` 3DS2 methods, so that `onAdditionalDetails` is handled in our `returnUrl`:
1. `onSubmit`:
  1.1. Make server request to send `POST /payments` to Adyen (from server)
  1.2. From response check if `response.resultCode === 'RedirectShopper'`
  1.3. If `Capacitor.isNativePlatform()` -> open url @capgo/inappbrowser's webview
    - Good to note that Adyen [recommends](https://docs.adyen.com/online-payments/web-best-practices#avoid-webviews) using `Android Custom Tabs` or `SFSafariViewController` to handle these (but in our case we modified webview to work better for us). To use these as recommended, you can use `InAppBrowser.open({ url: response.action.url })`, otherwise make sure the WebView is secure and able to handle 3DS2 authentication correctly.
  1.4. User is forwarded to authorize 3DS2 on Card issuer's webpage
2. Once user is authorized (or canceled) 3DS2 they are redirected to your `returnUrl` you specified for `POST /payments`. To make this work nicely you can setup universal links (iOS) or deep links (Android) to redirect back to your app
  2.1. Adyen redirects to your `returnUrl`  with `redirectResult` query parameter, so we handle these so that there is listener when WebView is loading our `returnUrl` it will close the WebView and handle the `redirectResults` from the Adyen's `returnUrl`
3. This redirectResult handling is pretty much same as `onAdditionalDetails` -call so it does the following:
  3.1. Send `redirectResults` to your serer to pass it to Adyen's `POST /payments/details` and handle continue based on the results (for example `Authorised`, `Cancelled`, `Refused`, and `Error` ([source](https://docs.adyen.com/online-payments/build-your-integration/payment-result-codes#final-payment-status)))
    3.1.1. `Authorised` -> Redirect to order confirmation
    3.1.2. `Cancelled` -> Notify and back to checkout
    3.1.3. `Refused` -> Notify and back to checkout
    3.1.4. `Error` -> Notify and back to checkout

So the key part here is to handle `RedirectShopper` `resultCode` via the flow above. To always handle with redirect you would need [these configs](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments#request-authenticationData-threeDSRequestData-nativeThreeDS) to Adyen's `POST /payments`

```typescript
{
  // ...other payment details/configs
  authenticationData: {
    threeDSRequestData: {
      nativeThreeDS: ThreeDSRequestData.NativeThreeDSEnum.Disabled
    },
  }
}
```

 In theory you could also handle 3DS2 with `nativeThreeDS` and then you would render that screen (rendering happens within Adyen's web SDK when you call `onSubmit()` -> `actions.resolve(response)`) and then actions in this new rendered screen will call `onAdditionalDetails()` -> server validation with `POST /payments/details` -> `actions.resolve(response)`. 

But we did not try out if Capacitor's internal WebView could handle Adyen's native 3DS2. Most likely this is not recommended (as there might be some restrictions in Capacitor's WebView), and right way to do so would be to extend the plugin we made to include also [native 3DS2 component](https://docs.adyen.com/online-payments/3d-secure/native-3ds2) from Adyen and show it when needed.

Something like:
```typescript
// Adyen Core configs for creating checkout session
const checkoutConfigs: CoreConfiguration = {
  // ...other configs
  onSubmit: async (state, component, actions): Promise<void> => {
    try {
      // Create POST /payments from your server
      const response = serverCall(state)
      if (Capacitor.isNativePlatform() {
        if (['ChallengeShopper', 'IdentifyShopper'].includes(response.resultCode)) {
          // Open new Adyen native component for 3DS2 authorization
          // await Adyen.handleNative3DS2(response)
      
          // Don't call actions.resolve(response) in this case, as it will otherwise redirect via Web SDK way
          // (otherwise it renders 3DS2 inside existing (web) Card component) and you would handle things inside onAdditionalDetails() -listener.
          return
        }
      
        if (response.resultCode === 'RedirectShopper') {
          // Open URL in Android Custom Tabs or SFSafariViewController (or in your own WebView if you are sure it works correctly)
          await Browser.open({ url: response.action.url })
  
          // We handle with capgo/inappbrowser's openWebView as such
          // set url change listener
          // await InAppBrowser.addListener('change', async (state) => {
          //  if (state.url === '<OUR RETURN URL (page that validates redirectResults parameter)>) {
          //    // this is actually handled by deep links on our end, but here is example what we do
          //    router.replace(state.url) // our single page app's navigation to processing page
          //
          //    // Close InAppBrowser to return back to main application
          //    await InAppBrowser.close()
          //  }
          // })
          //
          // await InAppBrowser.openWebView({
          //  url: response.action.url,
          //  // ...other relevant configs you want from InAppBrowser
          // })
      
          // Don't call actions.resolve(response) in this case, as it will otherwise redirect via Web SDK way
          // (it uses something like window.open() method to open redirect url in new tab on web browser)
          return
        }
      }
      
      // If not native platform and handled by native components by Adyen, you can call actions.resolve(response)
      // and it will follow web implementation inside Capacitor app's WebView (make sure it works for all the different payment methods you provide)
      actions.resolve(response)
    } catch (error) {
      // Call actions.reject() in case of errors, this will be handled in (web) Adyen's onError() -listener
      actions.reject()
    }
}
```

On our end, all the other payment methods than Bancontact we use uses `RedirectShopper` result code so it works nicely with only handling redirects in InAppBrowser. Bancontact renders QR code and redirect button inside the Web Component (and seems to work nicely). I think to make this whole thing working better on apps, we would need to add different native components from Adyen SDKs, but so far the ones we need works via WebView redirect as nice workaround. We might focus on adding these if we see benefits for UX from them.

I think next in line for us are Apple Pay and Google Pay, then maybe native Bancontact, iDEAL, etc. to render them better on apps.

---

You can check the ./example from the capacitor-adyen -plugin and install it on your app, it has similar boilerplate for this usecase what I described above (minus how we actually handle `onSubmit`, `onAdditionalDetails`, etc.) 😄 

This got pretty extensive answer, so hope it was clear enough to understand how it works on our end. I'm happy to answer on any additional questions though as it is somewhat complex and also usecase specific how to handle things!

**Comment by kristofferdamborg** [comment]
@eljass Such valuable information - thank you so much! I really appreciate it! 🙌
