### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#22]
## Plugin Request

**Name**: Contacts
**Package**: `@capacitor-community/contacts`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/apache/cordova-plugin-contacts (deprecated)

### Description

Plugin for fetching and managing device contacts.

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/799

**Comment by dwieeb** [comment]
https://github.com/capacitor-community/contacts 🤫

**Comment by thgick** [comment]
> https://github.com/capacitor-community/contacts 🤫

is only for fetching contacts, not for creating contacts like the mentioned deprecated cordova plugin.

**Comment by dwieeb** [comment]
@thgick Feel free to create a feature request in that repo. 😁

**Comment by Idrimi** [comment]
@thgick yeah create a feature request in the repo. What would you need creating and updating (and deleting?) contacts?

**Comment by thgick** [comment]
@Idrimi @dwieeb : Do you actually mean a new top level issue beside that proposal?
I ask because it seems a bit redundant to me since the title of the package already states to "manage" phone contacts, which are basically the features my request is about.

It would be great to be able to not only fetch all contacts,  but also to create, update and delete contacts.

The cordova plugin (which has performance and deprecation issues and not maintained anymore) offers a lot of fields when creating a contact.
Even if we not support all those fields in the beginning the following fields would be a great start to be able to manage contacts programmatically.

1 Name Information: namePrefix, givenName, middleName, familyName, nameSuffix
2 Work Information: jobTitle, departmentName, organizationName
3 labeled values which can be used in different contexts like 'home' and 'work':
  postalAddresses, emailAddresses, urlAddresses, Phone Information

It would also be great to apply an identifier when creating a new contact,
which can later be used to directly fetch the contact by using that identifier.

@Idrimi: it's nice to see that there's progress on that topic.

**Comment by imhoffd** [comment]
@thgick No, I meant in the [contacts repo](https://github.com/capacitor-community/contacts) itself. The Contacts plugin offered by the Capacitor Community could support managing contacts, instead of just fetching them.
