### ISSUE TITLE
Background-Geolocation

### ISSUE THREAD

**Issue by tripodsgames** [capacitor-community/proposals#40]
## Plugin Request

**Name**: Background-Geolocation
**Package**: `@capacitor-community/background-geolocation`

### Platform(s)

Android
IOS

### Existing Solutions

https://github.com/mauron85/cordova-plugin-background-geolocation (may have issues--see https://github.com/capacitor-community/proposals/issues/40#issuecomment-683200448)
https://github.com/transistorsoft/cordova-background-geolocation-lt (needs license)
https://github.com/seididieci/capacitor-backround-geolocation (only works on Android)

### Description

A plugin to provide Background Geolocation for IOS and Android.

**Comment by kevinboosten** [comment]
Worth mentioning that there is another well maintained existing solution: https://github.com/transistorsoft/cordova-background-geolocation-lt 
Eventually you'll need a license for your Android build, but this version definitively works 👍 . 
I tried to use the Mauron85 version in the past, but it was nog well maintained and had a lot of compatibility issues.

**Comment by imhoffd** [comment]
Thanks @Boosten! I added it to the original issue.

**Comment by vicmarcal** [comment]
I'd seriously remove https://github.com/mauron85/cordova-plugin-background-geolocation from the "Existing Solutions", the plugin code is totally outdated (it is using Swift 2, omg), the iOS and Android code is totally unmaintained (due the Permission's changes introduced in both Android and iOS)...Just look the Issues at such repo and people banging their heads against the wall. 

Transistorsoft alternative works way better but again, this is a PAID plugin.

Having a Background GPS feature is a must have for Capacitor. To begin with if you're trying to recreate RunKeeper or Endomondo, or a COVID Spaguetti app which recreates trajectories...you can't create it with Ionic + Capacitor, nor Ionic + Cordova.  

I had to create a project of this kind and I, sadly, had to use an alternative to Ionic because right now Cordova and Capacitor are lacking seriously this totally standard feature.

**Comment by noerw** [comment]
+1

I just found https://github.com/seididieci/capacitor-backround-geolocation, which currently only runs on Android.

**Comment by imhoffd** [comment]
@seididieci Would you be able to comment?

**Comment by seididieci** [comment]
Hi, I created the https://github.com/seididieci/capacitor-backround-geolocation because I had troubles with dependencies in cordova between some plugins and the geolocation. So I migrated the  APP I'm working to capacitor (thanks to the fact that any other plugin I need is included in cap) and I didn't want to have others dependencies problems.
Since I have not much sparse time and for now I need only to run thne APP on Android, my plugin is working only in this platform...
Everyone who wants to contribute to make the plugin work in iOS is welcome!

**Comment by diachedelic** [comment]
I just made a plugin for this, I'm happy to move it to into this org. https://github.com/diachedelic/capacitor-background-geolocation. It's similar to the cordova plugins mentioned above but without all the SQLite stuff and with better permissions handling.
@seididieci , sorry but I only found your plugin when I tried to publish to NPM!

**Comment by SalahAdDin** [comment]
@diachedelic two questions:
does this works when the application is inactive(in background)?
does it support ios?

**Comment by diachedelic** [comment]
@SalahAdDin 
> Capacitor plugin which lets you receive geolocation updates even while the app is backgrounded. Tested with Capacitor v2. iOS and Android platforms only.

**Comment by MInesGomes** [comment]
Anyone used this? https://github.com/capacitor-community/background-geolocation

**Comment by josuelmm** [comment]
**The best plugins is**
https://www.npmjs.com/package/cordova-background-geolocation-plugin

Use it with
@awesome-cordova-plugins/background-geolocation

```
$ npm install cordova-background-geolocation-plugin
$ npm install @awesome-cordova-plugins/background-geolocation 
$ ionic cap sync
```
